sudo: required
language: python
addons:
  postgresql: "9.5"
env:
  global:
    - BOTO_CONFIG='' ETCDVERSION=2.2.5
  matrix:
    - TEST_SUITE="python setup.py test"
    - TEST_SUITE="behave"
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1 postgresql-9.2 postgresql-9.3 postgresql-9.4
  - sudo apt-get -y autoremove
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get -y install postgresql-9.5
  - sudo /etc/init.d/postgresql stop
  - pip install -r requirements.txt
  - curl -L https://github.com/coreos/etcd/releases/download/v${ETCDVERSION}/etcd-v${ETCDVERSION}-linux-amd64.tar.gz | tar xz -C . --strip=1 --wildcards --no-anchored etcd
  - pip install behave codacy-coverage coverage coveralls 
script:
  - PATH=.:$PATH $TEST_SUITE
  - python setup.py flake8
after_success:
  - coveralls
  - if [[ -f coverage.xml ]]; then python-codacy-coverage -r coverage.xml; fi
